# This is a basic workflow to help you get started with Actions

name: Deploy NetPol

on:

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kubeval
        uses: "brpaz/gh-action-kubeval@v1.0.1"
        with:
         files: "src"
         github_token: "${{ secrets.GITHUB_TOKEN }}"
  SDW:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Call SDW Api
        run: echo Hello, world!
  deploy:
    runs-on: ubuntu-latest
    needs: SDW
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to cluster
        run: echo Hello, world!
